### ISSUE TITLE
[repo]: Research using `sistent` to sync version at once, instead of independently

### ISSUE THREAD

**Issue by nebula-aac** [layer5io/sistent#342]
**UPDATED**: Right now it is in `independent` mode, and I am testing some workflows to see how this works out.

In several different repositories that I have created in a Lerna workspace, I have found several things that occurs.

- Lerna will version and publish based on your commits history, and because of this, this also determines what is the next version from the git commits, on what version we should be bumping to. However, if the git commit history is not linear or clear enough for Lerna to understand, then the CHANGELOG generation can be conflicting in how PRs were made to separate packages and separate use cases, like chores or refactoring. 
- Lerna supports two versioning, fixed and independent. Independent mode allows free range on how you version, but Lerna assumes everything is to be bumped if you allowed this to be. You will have to control how Lerna version by either `patch`, `minor`, and `major`. Fixed mode will designate one version from `lerna.json`, and this is the same version across all packages, whether if there was any changes or not.

The key differences above is that in `Independent` mode, git tagging will only be `${package-name}@${version}`, where is in `Fixed` mode, git tagging will be `${package-name}@v${version}`

Other alternatives that can work with Lerna or without

- [ ] `release-it` - not exactly monorepo support, but there is an example
- [ ] `semantic-release`
- [ ] `standard-release` - has been changed to `release-please` and there is another fork
- [ ] `release-please` - GitHub Actions heavy, and relies heavily on `squash-merge`
- [ ] `changeset`

---

**[Contributor Guide](https://docs.meshery.io/project/contributing)**

- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
