### ISSUE TITLE
[utils]: Create `cytoscape` utils package

### ISSUE THREAD

**Issue by nebula-aac** [layer5io/sistent#379]
Create a package called `cytoscape-utils` which will house most if not all utilities pertaining to Cytoscape in Meshamp.

There are a lot of code surrounding this in `meshmap` so this ticket will be track what are things that are needed to be moved from `Meshmap` into here.

- [ ] `CytoscapeProvider` - React context provider for `cytoscape`
- [ ] `DesignerProvider` - React context provider for `designer`
- [ ] Meshmodal classes (optional)

---

**[Contributor Guide](https://docs.meshery.io/project/contributing)**

- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
