### ISSUE TITLE
[components]: Meshery UI components checklist

### ISSUE THREAD

**Issue by nebula-aac** [layer5io/sistent#402]
Checklist of major components to create and reuse

- [ ] https://github.com/layer5io/sistent/issues/399
- [x] https://github.com/layer5io/sistent/issues/385
- [ ] https://github.com/layer5io/sistent/issues/382
- [x] https://github.com/layer5io/sistent/issues/381
- [x] https://github.com/layer5io/sistent/issues/335
- [ ] https://github.com/layer5io/sistent/issues/334
- [x] https://github.com/layer5io/sistent/issues/318
- [x] https://github.com/layer5io/sistent/issues/313
- [ ] https://github.com/layer5io/sistent/issues/312
- [x] https://github.com/layer5io/sistent/issues/264
- [ ] #424

---

**[Contributor Guide](https://docs.meshery.io/project/contributing)**

- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by ameeetgaikwad** [comment]
Would like to help with component #381

**Comment by ameeetgaikwad** [comment]
Can you give me reference to which component i should refer? 

Also where should I create this `Stepper` component? @nebula-aac
